config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  #this needs to be password secured in real life
  
  root 'site#show'

  resources :books,  only: [:index, :create]
  resources :quotes, only: [:index, :create]
end

app/models/book.rb
class Book < ActiveRecord::Base
  def self.generate
    5000.times do
      Book.create(
        title:     Faker::Book.title,
        author:    Faker::Name.name,
        publisher: Faker::Book.publisher
      )
    end
  end
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  def self.generate
    5000.times do
      Quote.create(
        body:   Faker::Hacker.say_something_smart.capitalize,
        author: Faker::Name.name,
        title:  Faker::Name.title
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  add_flash_types :success
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def create
    GenerateBooksJob.perform_later

    redirect_to :back, success: 'The books were generated successfully.'
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.all
  end

  def create
    GenerateQuotesJob.(wait_until: Time.current.next_week).perform_later  
    redirect_to :back, success: 'The quotes were generated successfully.'
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link_to(body, url, html_options = {})
    if url == request.path
      link_to(body, url, class: 'active')
    else
      link_to(body, url)
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/books/index.html.erb
<div class="container-fluid books">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-10">
        <h1>Books</h1>
      </div>
      <div class="col-md-2">
        <%= link_to 'Generate', books_path, method: :post, class: 'btn btn-default btn-lg' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <hr>
        <% if @books.empty? %>
          <p>You don't have any books. To create some, click on the 'generate' button.</p>
        <% else %>
          <% @books.each do |book| %>
            <div class="book">
              <h5><%= book.created_at.strftime("%A, %B %d %Y") %></h5>
              <p><%= book.title %></p>
              <h4><%= book.author %></h4>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-2">
  </div>
</div>

app/views/layouts/_nav.html.erb
<% unless params[:controller] == "site" %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Loremore', root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= active_link_to 'Quotes', quotes_path %></li>
          <li><%= active_link_to 'Books', books_path %></li>          
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>

app/views/layouts/_notice.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>"><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loremore</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/notice' %>
    <%= yield %>
  </body>
</html>

app/views/quotes/index.html.erb
<div class="container-fluid quotes">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-10">
        <h1>Quotes</h1>
      </div>
      <div class="col-md-2">
        <%= link_to 'Generate', quotes_path, method: :post, class: 'btn btn-default btn-lg' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <hr>
        <% if @quotes.empty? %>
          <p>You don't have any quotes. To create some, click on the 'generate' button.</p>
        <% else %>
          <% @quotes.each do |quote| %>
            <div class="quote">
              <h5><%= quote.created_at.strftime("%A, %B %d %Y") %></h5>
              <p><%= quote.body %></p>
              <h4><%= quote.author %></h4>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-2">
  </div>
</div>

app/views/site/show.html.erb
<div class="container-fluid site">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
    <div class="leader">
      <h1>Loremore</h1>
      <h2>Free ideas for everyone.</h2>
      <div class="buttons">
        <%= link_to 'Quotes', quotes_path, class: 'btn btn-default btn-lg' %>
        <%= link_to 'Books',  books_path, class: 'btn btn-default btn-lg' %>
      </div>
    </div>
  </div>
  <div class="col-md-2">
  </div>
</div>